### ISSUE TITLE
Recalibration display error

### ISSUE THREAD

**Issue by griffey** [MeasureTheFuture/mothership#1]
When "recalibrate" is initiated in the web interface, the calibration frame is not displayed/and error occurs in the display. It is unclear from the interface if the frame was captured or not...it's possible that the calibration occurred and the issue is purely display, but that can't be determined from existing feedback on the public side.
<img width="1662" alt="screen shot 2016-08-13 at 6 43 41 pm" src="https://cloud.githubusercontent.com/assets/220018/17667057/d7282bc6-62c8-11e6-8860-fbd8137178ed.png">

**Comment by cfreeman** [comment]
This is fixed in v0.0.6, which is now available via https://github.com/MeasureTheFuture/installer 

Please test and re-open this issue if the problem persists.
