### ISSUE TITLE
Edison is killing the scout process

### ISSUE THREAD

**Issue by cfreeman** [MeasureTheFuture/mothership#10]
After about 4 or 5 hours, the OS on the Edison kills off the scout process. I suspect this is probably due to the amount of CPU the scout uses. I suspect I will be able to configure this not to happen.

**Comment by cfreeman** [comment]
(The webcam light remains on, even though the OS has killed the scout process).

**Comment by cfreeman** [comment]
@griffey Version 0.0.9 contains substantial improvements for this issue, needs some long running tests to see how it holds up.

**Comment by cfreeman** [comment]
@griffey Have had 0.0.9 running for 3 hours, memory usage is looking stable. If you could send me the scout_healths.json from your data download after a long running test I can double check the usage and close this one off.

**Comment by griffey** [comment]
Will update to .0.9 first thing and crank up a test to run through the
morning.

**Comment by cfreeman** [comment]
This is fixed in v0.0.10, which is now available via https://github.com/MeasureTheFuture/installer

Please test and re-open this issue if the problem persists.
