### ISSUE TITLE
White balance or brightness issue with camera

### ISSUE THREAD

**Issue by griffey** [MeasureTheFuture/mothership#2]
The calibration frame appears to be significantly under-exposed or off balance. Example frame attached was taken in a brightly lit room, for reference. 
<img width="1661" alt="screen shot 2016-08-13 at 6 43 31 pm" src="https://cloud.githubusercontent.com/assets/220018/17667096/08c28e56-62c9-11e6-8dd0-6593ecafd935.png">

**Comment by cfreeman** [comment]
This is fixed in v0.0.7, which is now available via https://github.com/MeasureTheFuture/installer

Please test and re-open this issue if the problem persists.
