### ISSUE TITLE
Heat map overlay error

### ISSUE THREAD

**Issue by griffey** [MeasureTheFuture/mothership#6]
Over time (more than an hour, need further testing to nail down when) the overlay begins to display black rather than transparent heat map. Images attached. 

https://www.dropbox.com/s/o77yrx61r1fqz7q/Screen%20Shot%202016-09-10%20at%2012.09.20%20PM.png?dl=0

https://www.dropbox.com/s/bpl6nb1vxsixnda/Screen%20Shot%202016-09-10%20at%201.20.18%20PM.png?dl=0

**Comment by cfreeman** [comment]
This is fixed in v0.0.6, which is now available via https://github.com/MeasureTheFuture/installer 

Please test and re-open this issue if the problem persists.
